{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b81f2436-f3b5-4495-a0b8-f2f0583d3aa8",
   "metadata": {},
   "outputs": [],
   "source": [
    "cols = ['序号', '系统匹配企业名称', '登记状态', '法定代表人', '联系电话', '注册资本', '成立日期', '统一社会信用代码',\n",
    "        '企业地址', '企业（机构）类型', '行业', '企业简介', '经营范围', '营业期限', '企业规模', '资质证书',\n",
    "        '是否录入供应商名录', '是否失信', '公司经营']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0ac8e08d-569d-4585-b006-b7d16eca45c5",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "from datetime import datetime\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "8327eef2-ee97-496d-afea-5d1c05a56cbe",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ====================== 全局配置 ======================\n",
    "st.set_page_config(page_title=\"供应商管理系统\", layout=\"wide\")\n",
    "DATA_FILE = \"supplier_data.xlsx\"\n",
    "LOG_FILE = \"operate_log.xlsx\"\n",
    "COLS = ['序号', '系统匹配企业名称', '登记状态', '法定代表人', '联系电话', '注册资本', '成立日期', '统一社会信用代码',\n",
    "        '企业地址', '企业（机构）类型', '行业', '企业简介', '经营范围', '营业期限', '企业规模', '资质证书',\n",
    "        '是否录入供应商名录', '是否失信', '公司经营']\n",
    "\n",
    "# 初始化数据文件\n",
    "def init_file():\n",
    "    if not os.path.exists(DATA_FILE):\n",
    "        df_empty = pd.DataFrame(columns=COLS)\n",
    "        df_empty.to_excel(DATA_FILE, index=False)\n",
    "    if not os.path.exists(LOG_FILE):\n",
    "        log_empty = pd.DataFrame(columns=[\"操作时间\", \"操作类型\", \"企业名称\", \"操作详情\"])\n",
    "        log_empty.to_excel(LOG_FILE, index=False)\n",
    "# 读取供应商数据\n",
    "def load_supplier():\n",
    "    df = pd.read_excel(r'C:\\Users\\lenovo\\Desktop\\供应商名录_正常版.xlsx', dtype=str)\n",
    "    df[\"序号\"] = pd.to_numeric(df[\"序号\"], errors=\"coerce\").fillna(0).astype(int)\n",
    "    return df\n",
    "\n",
    "# 保存供应商数据\n",
    "def save_supplier(df):\n",
    "    df_save = df.copy()\n",
    "    for col in df_save.columns:\n",
    "        df_save[col] = df_save[col].astype(str)\n",
    "    df_save.to_excel(DATA_FILE, index=False)\n",
    "\n",
    "# 写入操作日志\n",
    "def write_log(op_type, name, detail):\n",
    "    log_df = pd.read_excel(LOG_FILE)\n",
    "    new_log = pd.DataFrame({\n",
    "        \"操作时间\": [datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")],\n",
    "        \"操作类型\": [op_type],\n",
    "        \"企业名称\": [name],\n",
    "        \"操作详情\": [detail]\n",
    "    })\n",
    "    log_df = pd.concat([log_df, new_log], ignore_index=True)\n",
    "    log_df.to_excel(LOG_FILE, index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "29843085-efcc-47cc-a70b-09f85677d4e0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ====================== CRUD 功能函数 ======================\n",
    "def add_supplier(form_data):\n",
    "    df = load_supplier()\n",
    "    # 信用代码查重\n",
    "    code = form_data[\"统一社会信用代码\"]\n",
    "    if code in df[\"统一社会信用代码\"].astype(str).values:\n",
    "        return False, \"该统一社会信用代码已存在，禁止重复新增\"\n",
    "    # 生成序号\n",
    "    new_id = 1 if df.empty else int(df[\"序号\"].max()) + 1\n",
    "    form_data[\"序号\"] = new_id\n",
    "    new_row = pd.DataFrame([form_data])\n",
    "    df = pd.concat([df, new_row], ignore_index=True)\n",
    "    save_supplier(df)\n",
    "    write_log(\"新增\", form_data[\"系统匹配企业名称\"], \"新增供应商完整信息\")\n",
    "    return True, \"新增成功\"\n",
    "\n",
    "def edit_supplier(idx, form_data):\n",
    "    df = load_supplier()\n",
    "    old_name = df.loc[idx, \"系统匹配企业名称\"]\n",
    "    code = form_data[\"统一社会信用代码\"]\n",
    "    # 排除自身查重\n",
    "    exist_code = df[(df.index != idx) & (df[\"统一社会信用代码\"].astype(str) == code)]\n",
    "    if not exist_code.empty:\n",
    "        return False, \"统一社会信用代码已被其他企业占用\"\n",
    "    for col in COLS:\n",
    "        df.loc[idx, col] = form_data[col]\n",
    "    save_supplier(df)\n",
    "    write_log(\"编辑\", form_data[\"系统匹配企业名称\"], f\"原企业：{old_name}，修改基础信息\")\n",
    "    return True, \"修改成功\"\n",
    "\n",
    "def delete_supplier(index_list):\n",
    "    df = load_supplier()\n",
    "    del_names = df.loc[index_list, \"系统匹配企业名称\"].tolist()\n",
    "    df = df.drop(index=index_list).reset_index(drop=True)\n",
    "    # 重新排序序号\n",
    "    df[\"序号\"] = range(1, len(df)+1)\n",
    "    save_supplier(df)\n",
    "    for name in del_names:\n",
    "        write_log(\"删除\", name, \"删除整条供应商数据\")\n",
    "    return f\"成功删除{len(index_list)}条供应商数据\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "6fe29f3e-c098-4b20-9ca2-fa59538f183f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ====================== 可视化看板 ======================\n",
    "def show_dashboard(df_filter):\n",
    "    st.subheader(\"供应商数据可视化看板\")\n",
    "    # 指标卡片\n",
    "    c1,c2,c3,c4 = st.columns(4)\n",
    "    c1.metric(\"供应商总数\", len(df_filter))\n",
    "    c2.metric(\"失信供应商\", len(df_filter[df_filter[\"是否失信\"]==\"是\"]))\n",
    "    c3.metric(\"已录入名录\", len(df_filter[df_filter[\"是否录入供应商名录\"]==\"是\"]))\n",
    "    c4.metric(\"存续经营\", len(df_filter[df_filter[\"登记状态\"]==\"存续\"]))\n",
    "\n",
    "    # 图表分两排展示\n",
    "    row1_col1, row1_col2 = st.columns(2)\n",
    "    row2_col1, row2_col2 = st.columns(2)\n",
    "    row3_col1, row3_col2 = st.columns(2)\n",
    "\n",
    "    # 1.行业分布饼图\n",
    "    fig_industry = px.pie(df_filter, names=\"行业\", title=\"各行业供应商分布\")\n",
    "    row1_col1.plotly_chart(fig_industry, use_container_width=True)\n",
    "    # 2.失信状态饼图\n",
    "    fig_bad = px.pie(df_filter, names=\"是否失信\", title=\"失信企业占比\", color=\"是否失信\", color_discrete_map={\"是\":\"red\",\"否\":\"green\"})\n",
    "    row1_col2.plotly_chart(fig_bad, use_container_width=True)\n",
    "    # 3.企业规模柱状图\n",
    "    fig_size = px.bar(df_filter[\"企业规模\"].value_counts().reset_index(), x=\"企业规模\", y=\"count\", title=\"企业规模统计\")\n",
    "    row2_col1.plotly_chart(fig_size, use_container_width=True)\n",
    "    # 4.是否入库名录\n",
    "    fig_list = px.bar(df_filter[\"是否录入供应商名录\"].value_counts().reset_index(), x=\"是否录入供应商名录\", y=\"count\", title=\"供应商名录入库情况\")\n",
    "    row2_col2.plotly_chart(fig_list, use_container_width=True)\n",
    "    # 5.登记状态\n",
    "    fig_status = px.bar(df_filter[\"登记状态\"].value_counts().reset_index(), x=\"登记状态\", y=\"count\", title=\"企业登记状态分布\")\n",
    "    row3_col1.plotly_chart(fig_status, use_container_width=True)\n",
    "    # 6.成立年份趋势\n",
    "    df_filter[\"成立年份\"] = pd.to_datetime(df_filter[\"成立日期\"], errors=\"coerce\").dt.year\n",
    "    year_cnt = df_filter[\"成立年份\"].value_counts().sort_index().reset_index()\n",
    "    fig_year = px.line(year_cnt, x=\"成立年份\", y=\"count\", title=\"供应商成立年份趋势\")\n",
    "    row3_col2.plotly_chart(fig_year, use_container_width=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "901a0e82-6431-4e4a-bef4-86c0662d4bfc",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-07-02 08:53:43.726 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`\n",
      "2026-07-02 08:53:44.516 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\lenovo\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-07-02 08:53:45.110 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column 联系电话 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n"
     ]
    }
   ],
   "source": [
    "# ====================== 页面导航 ======================\n",
    "def main():\n",
    "    init_file()\n",
    "    df_all = load_supplier()\n",
    "    menu = st.sidebar.selectbox(\"系统功能菜单\", [\"数据看板\", \"供应商查询/编辑\", \"新增供应商\", \"批量删除\", \"操作审计日志\", \"数据导入导出\"])\n",
    "\n",
    "    # 全局筛选器\n",
    "    st.sidebar.divider()\n",
    "    st.sidebar.subheader(\"快速数据筛选\")\n",
    "    search_name = st.sidebar.text_input(\"企业名称模糊搜索\")\n",
    "    bad_filter = st.sidebar.selectbox(\"是否失信\", [\"全部\",\"是\",\"否\"])\n",
    "    list_filter = st.sidebar.selectbox(\"是否录入名录\", [\"全部\",\"是\",\"否\"])\n",
    "    industry_list = [\"全部\"] + sorted(df_all[\"行业\"].dropna().unique().tolist())\n",
    "    industry_filter = st.sidebar.selectbox(\"行业筛选\", industry_list)\n",
    "\n",
    "    # 数据过滤逻辑\n",
    "    df_view = df_all.copy()\n",
    "    if search_name:\n",
    "        df_view = df_view[df_view[\"系统匹配企业名称\"].str.contains(search_name, na=False, case=False)]\n",
    "    if bad_filter != \"全部\":\n",
    "        df_view = df_view[df_view[\"是否失信\"] == bad_filter]\n",
    "    if list_filter != \"全部\":\n",
    "        df_view = df_view[df_view[\"是否录入供应商名录\"] == list_filter]\n",
    "    if industry_filter != \"全部\":\n",
    "        df_view = df_view[df_view[\"行业\"] == industry_filter]\n",
    "\n",
    "    # 页面1：可视化看板\n",
    "    if menu == \"数据看板\":\n",
    "        st.title(\"供应商综合数据看板\")\n",
    "        show_dashboard(df_view)\n",
    "        st.divider()\n",
    "        st.subheader(\"筛选后供应商列表\")\n",
    "        st.dataframe(df_view, use_container_width=True)\n",
    "    # 页面2：查询+编辑\n",
    "    elif menu == \"供应商查询/编辑\":\n",
    "        st.title(\"供应商查询与信息修改\")\n",
    "        st.dataframe(df_view, use_container_width=True)\n",
    "        st.divider()\n",
    "        st.subheader(\"选中行编辑供应商信息\")\n",
    "        select_idx = st.number_input(\"输入表格左侧行号进行编辑\", min_value=0, max_value=len(df_view)-1 if len(df_view)>0 else 0, value=0)\n",
    "        if len(df_view) > 0:\n",
    "            edit_data = df_view.iloc[select_idx].to_dict()\n",
    "            with st.form(\"edit_form\"):\n",
    "                form_dict = {}\n",
    "                form_dict[\"系统匹配企业名称\"] = st.text_input(\"系统匹配企业名称\", value=edit_data[\"系统匹配企业名称\"])\n",
    "                form_dict[\"登记状态\"] = st.selectbox(\"登记状态\", [\"存续\",\"注销\",\"吊销\",\"在业\"], index=[\"存续\",\"注销\",\"吊销\",\"在业\"].index(edit_data[\"登记状态\"]) if edit_data[\"登记状态\"] in [\"存续\",\"注销\",\"吊销\",\"在业\"] else 0)\n",
    "                form_dict[\"法定代表人\"] = st.text_input(\"法定代表人\", value=edit_data[\"法定代表人\"])\n",
    "                form_dict[\"联系电话\"] = st.text_input(\"联系电话\", value=edit_data[\"联系电话\"])\n",
    "                form_dict[\"注册资本\"] = st.text_input(\"注册资本\", value=edit_data[\"注册资本\"])\n",
    "                form_dict[\"成立日期\"] = st.text_input(\"成立日期\", value=edit_data[\"成立日期\"])\n",
    "                form_dict[\"统一社会信用代码\"] = st.text_input(\"统一社会信用代码\", value=edit_data[\"统一社会信用代码\"])\n",
    "                form_dict[\"企业地址\"] = st.text_area(\"企业地址\", value=edit_data[\"企业地址\"])\n",
    "                form_dict[\"企业（机构）类型\"] = st.text_input(\"企业（机构）类型\", value=edit_data[\"企业（机构）类型\"])\n",
    "                form_dict[\"行业\"] = st.text_input(\"行业\", value=edit_data[\"行业\"])\n",
    "                form_dict[\"企业简介\"] = st.text_area(\"企业简介\", value=edit_data[\"企业简介\"])\n",
    "                form_dict[\"经营范围\"] = st.text_area(\"经营范围\", value=edit_data[\"经营范围\"])\n",
    "                form_dict[\"营业期限\"] = st.text_input(\"营业期限\", value=edit_data[\"营业期限\"])\n",
    "                form_dict[\"企业规模\"] = st.selectbox(\"企业规模\", [\"大型\",\"中型\",\"小型\",\"微型\"], index=[\"大型\",\"中型\",\"小型\",\"微型\"].index(edit_data[\"企业规模\"]) if edit_data[\"企业规模\"] in [\"大型\",\"中型\",\"小型\",\"微型\"] else 0)\n",
    "                form_dict[\"资质证书\"] = st.text_input(\"资质证书\", value=edit_data[\"资质证书\"])\n",
    "                form_dict[\"是否录入供应商名录\"] = st.selectbox(\"是否录入供应商名录\", [\"是\",\"否\"], index=0 if edit_data[\"是否录入供应商名录\"]==\"是\" else 1)\n",
    "                form_dict[\"是否失信\"] = st.selectbox(\"是否失信\", [\"是\",\"否\"], index=0 if edit_data[\"是否失信\"]==\"是\" else 1)\n",
    "                form_dict[\"公司经营\"] = st.text_area(\"公司经营备注\", value=edit_data[\"公司经营\"])\n",
    "                submit_edit = st.form_submit_button(\"保存修改\")\n",
    "            if submit_edit:\n",
    "                real_index = df_view.iloc[select_idx].name\n",
    "                flag, msg = edit_supplier(real_index, form_dict)\n",
    "                if flag:\n",
    "                    st.success(msg)\n",
    "                    st.rerun()\n",
    "                else:\n",
    "                    st.error(msg)\n",
    "    # 页面3：新增供应商\n",
    "    elif menu == \"新增供应商\":\n",
    "        st.title(\"新增供应商档案\")\n",
    "        with st.form(\"add_form\"):\n",
    "            form_dict = {}\n",
    "            form_dict[\"系统匹配企业名称\"] = st.text_input(\"系统匹配企业名称*\")\n",
    "            form_dict[\"登记状态\"] = st.selectbox(\"登记状态\", [\"存续\",\"注销\",\"吊销\",\"在业\"])\n",
    "            form_dict[\"法定代表人\"] = st.text_input(\"法定代表人*\")\n",
    "            form_dict[\"联系电话\"] = st.text_input(\"联系电话\")\n",
    "            form_dict[\"注册资本\"] = st.text_input(\"注册资本\")\n",
    "            form_dict[\"成立日期\"] = st.text_input(\"成立日期（例：2010-01-01）\")\n",
    "            form_dict[\"统一社会信用代码\"] = st.text_input(\"统一社会信用代码*\")\n",
    "            form_dict[\"企业地址\"] = st.text_area(\"企业地址\")\n",
    "            form_dict[\"企业（机构）类型\"] = st.text_input(\"企业（机构）类型\")\n",
    "            form_dict[\"行业\"] = st.text_input(\"行业*\")\n",
    "            form_dict[\"企业简介\"] = st.text_area(\"企业简介\")\n",
    "            form_dict[\"经营范围\"] = st.text_area(\"经营范围\")\n",
    "            form_dict[\"营业期限\"] = st.text_input(\"营业期限\")\n",
    "            form_dict[\"企业规模\"] = st.selectbox(\"企业规模\", [\"大型\",\"中型\",\"小型\",\"微型\"])\n",
    "            form_dict[\"资质证书\"] = st.text_input(\"资质证书（多份用逗号分隔）\")\n",
    "            form_dict[\"是否录入供应商名录\"] = st.selectbox(\"是否录入供应商名录\", [\"是\",\"否\"])\n",
    "            form_dict[\"是否失信\"] = st.selectbox(\"是否失信\", [\"是\",\"否\"])\n",
    "            form_dict[\"公司经营\"] = st.text_area(\"公司经营备注\")\n",
    "            submit_add = st.form_submit_button(\"提交新增供应商\")\n",
    "        if submit_add:\n",
    "            if not form_dict[\"系统匹配企业名称\"] or not form_dict[\"法定代表人\"] or not form_dict[\"统一社会信用代码\"] or not form_dict[\"行业\"]:\n",
    "                st.error(\"带*为必填项，不可为空！\")\n",
    "            else:\n",
    "                flag, msg = add_supplier(form_dict)\n",
    "                if flag:\n",
    "                    st.success(msg)\n",
    "                    st.rerun()\n",
    "                else:\n",
    "                    st.error(msg)\n",
    "\n",
    "    # 页面4：批量删除\n",
    "    elif menu == \"批量删除\":\n",
    "        st.title(\"批量删除供应商（谨慎操作）\")\n",
    "        st.dataframe(df_view, use_container_width=True)\n",
    "        del_input = st.text_input(\"输入需要删除的行号，逗号分隔，例：0,2,5\")\n",
    "        if st.button(\"确认批量删除\", type=\"primary\") and del_input:\n",
    "            try:\n",
    "                del_idx_list = [int(i.strip()) for i in del_input.split(\",\")]\n",
    "                real_del_idx = [df_view.iloc[i].name for i in del_idx_list]\n",
    "                tip = delete_supplier(real_del_idx)\n",
    "                st.success(tip)\n",
    "                st.rerun()\n",
    "            except Exception as e:\n",
    "                st.error(f\"输入格式错误：{str(e)}\")\n",
    "\n",
    "    # 页面5：审计操作日志\n",
    "    elif menu == \"操作审计日志\":\n",
    "        st.title(\"全量操作审计日志（审计整改可用）\")\n",
    "        log_df = pd.read_excel(LOG_FILE)\n",
    "        st.dataframe(log_df.sort_values(\"操作时间\", ascending=False), use_container_width=True)\n",
    "\n",
    "    # 页面6：导入导出\n",
    "    elif menu == \"数据导入导出\":\n",
    "        st.title(\"供应商台账导入导出\")\n",
    "        # 导出\n",
    "        st.download_button(\"导出当前筛选数据Excel\", data=df_view.to_csv(index=False, encoding=\"utf-8-sig\"), file_name=\"供应商筛选台账.csv\")\n",
    "        st.download_button(\"导出全部供应商完整台账\", data=df_all.to_csv(index=False, encoding=\"utf-8-sig\"), file_name=\"全部供应商台账.csv\")\n",
    "        # 批量导入\n",
    "        upload_file = st.file_uploader(\"上传Excel批量新增供应商（需和表头字段一致）\")\n",
    "        if upload_file:\n",
    "            upload_df = pd.read_excel(upload_file)\n",
    "            # 只保留匹配字段\n",
    "            upload_df = upload_df[[c for c in COLS if c in upload_df.columns]]\n",
    "            df_merge = pd.concat([df_all, upload_df], ignore_index=True)\n",
    "            # 去重（信用代码唯一）\n",
    "            df_merge = df_merge.drop_duplicates(subset=\"统一社会信用代码\", keep=\"first\")\n",
    "            df_merge[\"序号\"] = range(1, len(df_merge)+1)\n",
    "            save_supplier(df_merge)\n",
    "            st.success(f\"批量导入完成，本次新增{len(upload_df)}条供应商数据\")\n",
    "            st.rerun()\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "78d40c64-25a3-43d3-ac26-077fc17927ed",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "77aefb40-189c-4ec5-bb0f-8ce50770db3e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
